package mypack;
// Generated Jun 4, 2021 7:23:24 PM by Hibernate Tools 4.3.1

import java.sql.*;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.List;




/**
 * Userdetails generated by hbm2java
 */
public class Userdetails  implements java.io.Serializable {
     private Integer id;
     private String firstname;
     private String lastname;
     private String phoneNumber;
     private String address;
     private String city;
     private String pin;

    public Userdetails() {
    }
    
    public Userdetails(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Userdetails(String firstname, String lastname, String phoneNumber, String address, String city, String pin) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.phoneNumber = phoneNumber;
       this.address = address;
       this.city = city;
       this.pin = pin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }

    public List getfnameDb(String fname) {
        List<Userdetails> list = new ArrayList<>();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("1");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook","root","");
        System.out.println("2");
        Statement stmt = con.createStatement();
        String sql = "select * from userdetails where Firstname=?";
        PreparedStatement st = con.prepareStatement(sql);
        st.setString(1, fname);
        ResultSet rs = st.executeQuery();
        while(rs.next())
        {
            Userdetails ud = new Userdetails();
            ud.setId(rs.getInt(1));
            ud.setFirstname(rs.getString(2));
            ud.setLastname(rs.getString(3));
            ud.setPhoneNumber(rs.getString(4));
            ud.setAddress(rs.getString(5));
            ud.setCity(rs.getString(6));
            ud.setPin(rs.getString(7));
            list.add(ud);
        }
        }
        catch(Exception e) {
            System.out.println("ERROR");
            System.out.println(e);
        }
        return list;
    }
    
    public List getlnameDb(String lname) {
        List<Userdetails> list = new ArrayList<>();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("1");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook","root","");
        System.out.println("2");
        Statement stmt = con.createStatement();
        String sql = "select * from userdetails where Lastname=?";
        PreparedStatement st = con.prepareStatement(sql);
        st.setString(1, lname);
        ResultSet rs = st.executeQuery();
        while(rs.next())
        {
            Userdetails ud = new Userdetails();
            ud.setFirstname(rs.getString(2));
            ud.setLastname(rs.getString(3));
            ud.setPhoneNumber(rs.getString(4));
            ud.setAddress(rs.getString(5));
            ud.setCity(rs.getString(6));
            ud.setPin(rs.getString(7));
            list.add(ud);
        }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        return list;
    }
    
    public List getphnoDb(String phno) {
        List<Userdetails> list = new ArrayList<>();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("1");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook","root","");
        System.out.println("2");
        Statement stmt = con.createStatement();
        String sql = "select * from userdetails where PhoneNumber=?";
        PreparedStatement st = con.prepareStatement(sql);
        st.setString(1, phno);
        ResultSet rs = st.executeQuery();
        while(rs.next())
        {
            Userdetails ud = new Userdetails();
            ud.setFirstname(rs.getString(2));
            ud.setLastname(rs.getString(3));
            ud.setPhoneNumber(rs.getString(4));
            ud.setAddress(rs.getString(5));
            ud.setCity(rs.getString(6));
            ud.setPin(rs.getString(7));
            list.add(ud);
        }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        return list;
    }
    
    public List getaddrDb(String addr) {
        List<Userdetails> list = new ArrayList<>();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("1");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook","root","");
        System.out.println("2");
        Statement stmt = con.createStatement();
        String sql = "select * from userdetails where Address=?";
        PreparedStatement st = con.prepareStatement(sql);
        st.setString(1, addr);
        ResultSet rs = st.executeQuery();
        while(rs.next())
        {
            Userdetails ud = new Userdetails();
            ud.setFirstname(rs.getString(2));
            ud.setLastname(rs.getString(3));
            ud.setPhoneNumber(rs.getString(4));
            ud.setAddress(rs.getString(5));
            ud.setCity(rs.getString(6));
            ud.setPin(rs.getString(7));
            list.add(ud);
        }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        return list;
    }
    
    public List getcityDb(String city) {
        List<Userdetails> list = new ArrayList<>();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("1");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook","root","");
        System.out.println("2");
        Statement stmt = con.createStatement();
        String sql = "select * from userdetails where City=?";
        PreparedStatement st = con.prepareStatement(sql);
        st.setString(1, city);
        ResultSet rs = st.executeQuery();
        while(rs.next())
        {
            Userdetails ud = new Userdetails();
            ud.setFirstname(rs.getString(2));
            ud.setLastname(rs.getString(3));
            ud.setPhoneNumber(rs.getString(4));
            ud.setAddress(rs.getString(5));
            ud.setCity(rs.getString(6));
            ud.setPin(rs.getString(7));
            list.add(ud);
        }
        System.out.println("3");
        }
        catch(Exception e) {
            System.out.println(e);
        }
        return list;
    }
    
    public List getpinDb(String pin) {
        List<Userdetails> list = new ArrayList<>();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("1");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook","root","");
        System.out.println("2");
        Statement stmt = con.createStatement();
        String sql = "select * from userdetails where Pin=?";
        PreparedStatement st = con.prepareStatement(sql);
        st.setString(1, pin);
        ResultSet rs = st.executeQuery();
        while(rs.next())
        {
            Userdetails ud = new Userdetails();
            ud.setFirstname(rs.getString(2));
            ud.setLastname(rs.getString(3));
            ud.setPhoneNumber(rs.getString(4));
            ud.setAddress(rs.getString(5));
            ud.setCity(rs.getString(6));
            ud.setPin(rs.getString(7));
            list.add(ud);
        }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        return list;
    }
    
    public boolean delete(String phno) {
        boolean del = false;
        try{
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("1");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook","root","");
        System.out.println("2");
        Statement stmt = con.createStatement();
        String sql = "delete from userdetails where PhoneNumber=?";
        PreparedStatement st = con.prepareStatement(sql);
        st.setString(1, phno);
        int rs = st.executeUpdate();
        System.out.println("3");
        if(rs>0){
            del = true;
        }else{
            del = false;
        }
        System.out.println("deleted "+del);   
        }
        catch(Exception e) {
            System.out.println(e);
            del = false;
        }
        return del;
    }


}


