package mypack;
// Generated Jun 4, 2021 7:23:24 PM by Hibernate Tools 4.3.1

import java.sql.*;




/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String username;
     private String password;

    public User() {
    }

	
    public User(String name, String password) {
        this.name = name;
        this.password = password;
    }
    public User(String name, String username, String password) {
       this.name = name;
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public boolean userlogin(String uname, String pswd) {
        boolean op=false;
        String undb,psdb;
        try{
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("1");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook","root","");
        System.out.println("2");
        System.out.println("uname :"+uname);
        System.out.println("pswd :"+pswd);
        Statement stmt = con.createStatement();
        String sql = "select username,password from user where username=?";
        PreparedStatement st = con.prepareStatement(sql);
        st.setString(1, uname);
        ResultSet rs = st.executeQuery();
        if(rs.next())
        {
            if(uname.equals(rs.getString(1)) && pswd.equals(rs.getString(2))) {
                op = true;
                System.out.println("true if");
            }
            else{
                op = false;
                System.out.println("false else");
            }
        }
        
        return op;
        }
        catch(Exception e) {
            op = false;
            System.out.println(e);
            return op;
        }
    }


}


